[package]
name = "prisma-query"
version = "0.1.0"
authors = [
    "Julius de Bruijn <bruijn@prisma.io>",
    "Dominic Petrick <petrick@prisma.io>",
    "Katharina Fey <kookie@spacekookie.de>",
    "Emanuel Jöbstl <emanuel.joebstl@gmail.com>"
]
edition = "2018"
readme  = "README.md"
license = "Apache-2.0"
description = "An abstraction layer for SQL databases."
repository  = "https://github.com/prisma/prisma-query/"
homepage    = "https://github.com/prisma/prisma-query/"
keywords    = ["mysql", "postgresql", "sqlite", "sql"]
documentation = "https://docs.rs/prisma-query/"

[features]
default = ["rusqlite-0_19", "json-1", "postgresql-0_16", "uuid-0_7", "chrono-0_4", "mysql-16" ]
rusqlite-0_19 = ["rusqlite", "r2d2_sqlite", "r2d2", "libsqlite3-sys"]
json-1 = ["serde_json"]
postgresql-0_16 = ["postgres", "rust_decimal", "r2d2", "r2d2_postgres", "native-tls", "tokio-postgres", "tokio-postgres-native-tls", "array"]
uuid-0_7 = ["uuid"]
chrono-0_4 = ["chrono"]
mysql-16 = ["mysql", "r2d2", "r2d2_mysql"]
array = []

[dependencies]
url = "1.7"
failure = "0.1"
metrics = "0.11"
failure_derive = "0.1"
percent-encoding = "2"
debug_stub_derive = "0.3"
lazy_static = "1.3"
num_cpus = "1.10"

uuid = { version = "0.7", optional = true }
chrono = { version = "0.4", optional = true }
serde_json = { version = "1.0", optional = true }
log = { version = "0.4", features = ["release_max_level_trace"] }
rust_decimal = { git = "https://github.com/pimeys/rust-decimal.git", branch = "update_psql", optional = true, features = ["postgres"] }

r2d2 = {  version = "0.8", optional = true }
r2d2_mysql= { version = "*", optional = true }
r2d2_sqlite = { version = "0.11", optional = true }
r2d2_postgres = { git = "https://github.com/pimeys/r2d2-postgres", branch = "std-futures", optional = true }

rusqlite = { version = "0.19", features = ["chrono", "bundled"], optional = true }
libsqlite3-sys = { version = "0.15", default-features = false, features = ["bundled"], optional = true }

postgres = { git = "https://github.com/pimeys/rust-postgres", branch = "std-futures", features = ["with-serde_json-1", "with-chrono-0_4", "with-uuid-0_7"], optional = true}
native-tls = { version = "0.2", optional = true }
tokio-postgres = { git = "https://github.com/pimeys/rust-postgres", branch = "std-futures", optional = true }
tokio-postgres-native-tls = { package = "postgres-native-tls", git = "https://github.com/pimeys/rust-postgres", branch = "std-futures", optional = true }

mysql = { version = "16", optional = true }
